defaultNamespace: kubeinvaders

labels:
  app: chaos

helm:
  repo:  https://lucky-sideburn.github.io/helm-charts/
  chart: kubeinvaders
  version: 1.9.6
  releaseName: kubeinvaders
  values:
    ingress:
      enabled: true
      hostName: chaos.kube.lol
      className: "traefik"
      secretName: kube-lol
    deployment:
      replicaCount: 3
      image:
        repository: harbor.atoy.dev/public/kubeinvaders
        tag: v1.9.6
    config:
      target_namespace: "demo-namespace,kubeinvaders"
